config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :invoices
  get "/posts/tags/new" => "posts/tags#new", :as => :posts_tags

  resources :posts do
    member do
      resources "posts/tags", only: [:create, :destroy], as: :post_tags
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "application#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  broadcasts_refreshes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def welcome
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :update]

  def index
    @photos = Photo.all
  end

  def show
  end

  def update
    @photo.increment(:likes_count)
    @photo.save
    redirect_to photo_path(@photo)
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable_table_header(title, column, path_method, **)
    content_tag(:th, class: "invoices__th") do
      sortable_column(title, column, path_method)
    end
  end

  def sortable_column(title, column, path_method, **)
    direction = (column.to_s == params[:sort].to_s && params[:direction] == "asc") ? "desc" : "asc"

    query_params = request.query_parameters.merge(sort: column, direction: direction)

    path = send(path_method, query_params)
    link_to(path, data: {turbo_action: "advance"}, class: "flex items-center", **) do
      concat title
      concat sort_icon(column)
    end
  end

  def sort_icon(column)
    return unless params[:sort].to_s == column.to_s

    if params[:direction] == "asc"
      svg_icon("M5 15l7-7 7 7")
    else
      svg_icon("M19 9l-7 7-7-7")
    end
  end

  def svg_icon(path_d)
    content_tag(:svg, xmlns: "http://www.w3.org/2000/svg", class: "ml-1 inline w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor") do
      "<path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='#{path_d}'></path>".html_safe
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_footer.html.erb
<footer class="z-10 bg-white">
  <div class="px-6 py-10 mx-auto overflow-hidden max-w-7xl sm:py-12 lg:px-8">
    <div class="mt-10 text-xs leading-5 text-center text-gray-500">
      <a href="https://avi.nyc" title="avi.nyc">avi.nyc</a>
      <div class="heart">❤️</div>
      <span>Rails</span>
    </div>

    <div class="flex justify-center mt-10 space-x-10">
      <a href="https://code.avi.nyc" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Hashnode</span>
        <svg class="w-6 h-6" viewBox="0 0 337 337" fill="currentColor">\
          <path fill-rule="evenodd" clip-rule="evenodd" d="M23.155 112.598c-30.873 30.874-30.873 80.93 0 111.804l89.443 89.443c30.874 30.873 80.93 30.873 111.804 0l89.443-89.443c30.873-30.874 30.873-80.93 0-111.804l-89.443-89.443c-30.874-30.873-80.93-30.873-111.804 0l-89.443 89.443zm184.476 95.033c21.612-21.611 21.612-56.651 0-78.262-21.611-21.612-56.651-21.612-78.262 0-21.612 21.611-21.612 56.651 0 78.262 21.611 21.612 56.651 21.612 78.262 0z" fill="currentColor"/>
        </svg>
        <a href="https://x.com/aviflombaum" class="text-gray-400 hover:text-gray-500">
          <span class="sr-only">X</span>
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M13.6823 10.6218L20.2391 3H18.6854L12.9921 9.61788L8.44486 3H3.2002L10.0765 13.0074L3.2002 21H4.75404L10.7663 14.0113L15.5685 21H20.8131L13.6819 10.6218H13.6823ZM11.5541 13.0956L10.8574 12.0991L5.31391 4.16971H7.70053L12.1742 10.5689L12.8709 11.5655L18.6861 19.8835H16.2995L11.5541 13.096V13.0956Z" />
          </svg>
        </a>
        <a href="https://github.com/aviflombaum" class="text-gray-400 hover:text-gray-500">
          <span class="sr-only">GitHub</span>
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "avi.nyc ❤️ Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="view-transition" content="same-origin"/>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script defer data-domain="rails.avi.nyc" src="https://a.wip.dev/js/script.js"></script>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/photos/_photo.html.erb
<%= content_tag :div, 
  class: "photo-viewer", 
  style: "view-transition-name: #{dom_id(photo)}", 
  id: dom_id(photo) do %>
  <div class="photo-viewer__container">
    <img class="photo-viewer__image" src="<%= photo.url %>" alt="<%= photo.name %>">
    <div class="photo-viewer__back-link">
      <%= link_to photos_path, class: "back-link__link" do %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="back-link__icon"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/>
        </svg>
      <% end %>
    </div>
    <div class="photo-viewer__like-button" style="view-transition-name: zoom">
      <%= form_for(photo) do |f| %>
        <%= f.button type: 'submit', class: "like-button__link" do %>
          <span class="like-button__icon">❤️</span>
          <span class="like-button__count"><%= photo.likes_count %></span>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/photos/index.html.erb
<div class="grid grid-cols-2 gap-4 md:grid-cols-4">
  <% @photos.each_slice(3) do |photo_group| %>
    <div class="grid gap-4">
      <% photo_group.each do |photo| %>
        <div>
          <%= link_to photo_path(photo) do %>
            <img
              class="h-auto max-w-full rounded-lg"
              src="<%= photo.url %>"
              alt="<%= photo.name %>"
              style="view-transition-name: photo_<%= photo.id %>"
            >
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/photos/show.html.erb
<%= turbo_stream_from @photo %>

<%= render @photo %>